import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { JsonLd } from "../../components/JsonLd";
import { SiteFooter } from "../../components/SiteFooter";
import { SiteHeader } from "../../components/SiteHeader";
import { siteUrl } from "../../lib/site";

const articles = {
  "recuperare-clienti-centro-estetico": { title: "Come recuperare le clienti che non tornano", description: "Metodo pratico per riattivare clienti inattive in un centro estetico senza inviare messaggi generici.", intro: "Recuperare una cliente non significa mandare la stessa promozione a tutta la rubrica. Significa capire perché potrebbe essere il momento giusto per tornare e offrirle un passo utile.", sections: [["1. Scegli le persone giuste", "Dividi le clienti per ultimo appuntamento, trattamento svolto e percorso lasciato in sospeso. Parti da chi ha un motivo concreto per tornare."], ["2. Dai un motivo credibile", "Un controllo, la continuità di un percorso o una disponibilità adatta sono più efficaci di uno sconto generico."], ["3. Scrivi come una persona", "Usa il nome, ricorda il contesto e fai una domanda semplice. Il messaggio deve sembrare attenzione, non pressione."], ["4. Misura l’esito", "Segna risposte, appuntamenti e valore recuperato. Dopo alcune settimane saprai quali richiami funzionano davvero."]] },
  "riempire-orari-liberi": { title: "Come riempire un orario libero senza fare sconti", description: "Strategie per riempire i buchi in agenda di un centro estetico proteggendo il valore dei trattamenti.", intro: "Uno spazio libero non richiede sempre uno sconto. Spesso basta proporlo alla persona adatta, con il servizio adatto e nel momento in cui può accettare.", sections: [["1. Parti dalla compatibilità", "Considera durata dello spazio, servizio, zona trattata e fase del percorso."], ["2. Contatta poche persone", "Una lista breve e rilevante protegge la relazione e riduce i messaggi inutili."], ["3. Presenta una comodità", "Comunica che si è liberata una disponibilità adatta, senza creare urgenza artificiale."], ["4. Impara dai risultati", "Registra chi accetta, chi preferisce altri orari e chi non vuole ricevere queste proposte."]] },
  "messaggi-whatsapp-centro-estetico": { title: "Messaggi WhatsApp per centri estetici: esempi umani", description: "Esempi di messaggi WhatsApp per richiamare clienti, proporre orari liberi e seguire i trattamenti.", intro: "Un buon messaggio WhatsApp è breve, personale e utile. Spiega perché stai scrivendo e lascia alla cliente una scelta semplice, senza insistenza.", sections: [["Cliente che non torna", "Ciao Martina, come stai? È passato un po’ di tempo dall’ultimo trattamento viso. Se vuoi riprendere il percorso, questa settimana abbiamo due disponibilità comode. Vuoi che te le mandi?"], ["Orario appena liberato", "Ciao Giulia, si è liberato un posto domani alle 15:30, della durata giusta per la tua prossima seduta. Può esserti utile?"], ["Controllo dopo il trattamento", "Ciao Elena, come ti sei trovata dopo il trattamento di venerdì? Quando hai un momento, raccontaci come sta andando."], ["Regola importante", "Non inventare confidenza e non nascondere lo scopo del messaggio. Usa sempre informazioni reali e lascia una via d’uscita semplice."]] },
} as const;

export function generateStaticParams() { return Object.keys(articles).map((slug) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const article = articles[slug as keyof typeof articles]; if (!article) return {}; return { title: article.title, description: article.description, alternates: { canonical: `/risorse/${slug}` } }; }
export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const article = articles[slug as keyof typeof articles]; if (!article) notFound(); const schema = { "@context": "https://schema.org", "@type": "Article", headline: article.title, description: article.description, inLanguage: "it-IT", author: { "@type": "Organization", name: "AgendaPiena AI" }, publisher: { "@type": "Organization", name: "AgendaPiena AI" }, mainEntityOfPage: `${siteUrl}/risorse/${slug}` }; return <main><JsonLd data={schema} /><SiteHeader /><article className="article-page"><span className="eyebrow">Guida AgendaPiena</span><h1>{article.title}</h1><p className="article-lead">{article.intro}</p>{article.sections.map(([title, copy]) => <section key={title}><h2>{title}</h2><p>{copy}</p></section>)}<aside><strong>Vuoi applicarlo ai dati del tuo centro?</strong><p>AgendaPiena AI trova ogni giorno le persone giuste e prepara i messaggi da approvare.</p><a href="/contatti">Prenota una demo</a></aside></article><SiteFooter /></main>; }

