import type { Metadata } from "next";
import { PageIntro } from "../../components/PageIntro";
import { SiteFooter } from "../../components/SiteFooter";
import { SiteHeader } from "../../components/SiteHeader";

export const metadata: Metadata = { title: "Assistente AI per centri estetici", description: "Recupera clienti, riempi gli orari liberi e segui pacchetti e trattamenti con AgendaPiena AI per centri estetici.", alternates: { canonical: "/settori/centri-estetici" } };

export default function BeautyPage() { return <main><SiteHeader /><PageIntro eyebrow="Per centri estetici" title="Ogni cliente dimenticata è un appuntamento possibile." description="AgendaPiena AI aiuta il centro a seguire richiami, pacchetti, trattamenti ricorrenti e spazi liberi. Lo fa con messaggi personali e con il controllo costante del titolare." secondary={{ label: "Vedi come funziona", href: "/come-funziona" }} /><section className="section"><div className="section-title"><span>Casi d’uso</span><h2>Dove recupera valore.</h2></div><div className="benefit-grid"><article className="benefit-item"><span>01</span><h3>Epilazione laser</h3><p>Richiama chi ha interrotto il percorso e propone lo spazio giusto in base alla zona e alla durata.</p></article><article className="benefit-item"><span>02</span><h3>Trattamenti viso e corpo</h3><p>Ricorda controlli, sedute successive e mantenimento senza comunicazioni fredde o uguali per tutti.</p></article><article className="benefit-item"><span>03</span><h3>Pacchetti incompleti</h3><p>Individua crediti e sedute rimaste ferme, poi prepara un invito discreto a riprendere.</p></article><article className="benefit-item"><span>04</span><h3>Orari liberi</h3><p>Abbina un posto disponibile alle clienti che potrebbero accettarlo, senza scontare il valore del servizio.</p></article></div></section><section className="plain-band"><div><span>Il vantaggio</span><h2>Più continuità, non più messaggi.</h2></div><p>Il punto non è contattare tutti. È scegliere le persone giuste, nel momento giusto, con un motivo utile e credibile.</p></section><SiteFooter /></main>; }

