import type { Metadata } from "next";
import { JsonLd } from "../components/JsonLd";
import { PageIntro } from "../components/PageIntro";
import { SiteFooter } from "../components/SiteFooter";
import { SiteHeader } from "../components/SiteHeader";
import { contactHref, siteUrl } from "../lib/site";

export const metadata: Metadata = { title: "Prezzi AgendaPiena AI per centri estetici", description: "Configurazione da €790 e servizio da €390 al mese. Scopri cosa comprende AgendaPiena AI e prenota una demo senza impegno.", alternates: { canonical: "/prezzi" } };

export default function PricingPage() { const schema = { "@context": "https://schema.org", "@type": "Product", name: "AgendaPiena AI", description: "Assistente AI per centri estetici", offers: { "@type": "Offer", price: "390", priceCurrency: "EUR", url: `${siteUrl}/prezzi`, availability: "https://schema.org/InStock" } }; return <main><JsonLd data={schema} /><SiteHeader /><PageIntro eyebrow="Prezzi chiari" title="Un investimento semplice da misurare." description="Prima configuriamo AgendaPiena sui tuoi servizi e sui tuoi dati. Poi misuriamo clienti recuperati, appuntamenti fissati e valore generato." /><section className="pricing-page"><article><span>Configurazione iniziale</span><strong>€790</strong><p>Una sola volta</p><ul><li>Analisi del centro e degli obiettivi</li><li>Importazione e controllo dei dati</li><li>Impostazione del tono dei messaggi</li><li>Prime tre azioni guidate</li><li>Formazione del titolare o dello staff</li></ul></article><article className="featured-price"><span>Servizio continuativo</span><strong>€390</strong><p>al mese</p><ul><li>Analisi quotidiana di clienti e agenda</li><li>Messaggi personalizzati da approvare</li><li>Schermata mobile per il team</li><li>Report settimanale dei risultati</li><li>Assistenza e miglioramento continuo</li></ul><a href={contactHref}>Richiedi una demo</a></article></section><section className="faq-section"><span>Prima di decidere</span><h2>Domande sui prezzi</h2><details><summary>Ci sono costi nascosti?</summary><p>No. Eventuali integrazioni speciali o grandi volumi vengono valutati e approvati prima del lavoro.</p></details><details><summary>Posso partire con una sola sede?</summary><p>Sì. Consigliamo di iniziare con una sede, misurare i risultati e poi estendere il servizio.</p></details><details><summary>Quanto devo recuperare per coprire il costo?</summary><p>Dipende dal valore medio dei tuoi trattamenti. Durante la demo calcoliamo insieme il punto di pareggio usando i tuoi numeri.</p></details></section><SiteFooter /></main>; }

