import type { Metadata } from "next";
import { PageIntro } from "../../components/PageIntro";
import { SiteFooter } from "../../components/SiteFooter";
import { SiteHeader } from "../../components/SiteHeader";

export const metadata: Metadata = { title: "Assistente AI per cliniche estetiche e longevità", description: "Follow-up, controlli e continuità dei percorsi per cliniche estetiche e centri di longevità, con supervisione umana.", alternates: { canonical: "/settori/cliniche-estetiche" } };

export default function ClinicsPage() { return <main><SiteHeader /><PageIntro eyebrow="Cliniche estetiche e longevità" title="La relazione continua anche tra una visita e l’altra." description="AgendaPiena AI aiuta il team a non perdere follow-up, controlli e percorsi di mantenimento. Ogni comunicazione resta sotto supervisione e separata dalle decisioni cliniche." secondary={{ label: "Parliamo del tuo caso", href: "/contatti" }} /><section className="section"><div className="section-title"><span>Supporto operativo</span><h2>Più ordine nei passaggi non clinici.</h2></div><div className="benefit-grid"><article className="benefit-item"><span>01</span><h3>Follow-up programmati</h3><p>Prepara promemoria e richieste di riscontro nei tempi indicati dalla struttura.</p></article><article className="benefit-item"><span>02</span><h3>Controlli da fissare</h3><p>Segnala le persone da ricontattare e aiuta la segreteria a proporre una disponibilità.</p></article><article className="benefit-item"><span>03</span><h3>Percorsi di mantenimento</h3><p>Mantiene continuità nei programmi estetici e di benessere senza affidarsi alla memoria.</p></article><article className="benefit-item"><span>04</span><h3>Passaggio al personale</h3><p>Le richieste sensibili o cliniche vengono indirizzate subito a una persona qualificata.</p></article></div></section><section className="notice"><strong>Importante</strong><p>AgendaPiena AI supporta organizzazione e comunicazione. Non formula diagnosi, non prescrive trattamenti e non sostituisce il personale sanitario.</p></section><SiteFooter /></main>; }

